---
grails:
  profile: web-plugin
  codegen:
    defaultPackage: grails.plugin.i18nEnums
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

